# Generated by Django 4.1.7 on 2023-08-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kullanici',
            options={},
        ),
        migrations.RemoveField(
            model_name='kullanici',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='kullanici',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='kullanici',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='kullanici',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='kullanici',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='kullanici',
            name='last_name',
        ),
        migrations.AddField(
            model_name='kullanici',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
