# Generated by Django 4.1.7 on 2023-09-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_kullanici_options_remove_kullanici_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='kullanici',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Username'),
        ),
    ]
