# Generated by Django 4.1.7 on 2023-09-01 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_created_by_alter_board_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideapin',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idea_pins', to='board.board'),
        ),
    ]
