# Generated by Django 4.1.7 on 2023-09-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_uploadedmedia_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedmedia',
            name='file',
            field=models.FileField(upload_to='uploaded_media/'),
        ),
    ]
