# Generated by Django 4.1.7 on 2023-09-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_uploadedmedia_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
