# Generated by Django 4.1.7 on 2023-09-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_pin_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
