# Generated by Django 4.2.4 on 2023-09-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_reaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='likes',
        ),
    ]
