# Generated by Django 4.2.4 on 2023-09-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_remove_pin_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
