# Generated by Django 4.2.4 on 2023-09-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_pin_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='video',
        ),
        migrations.AddField(
            model_name='ideapin',
            name='materials',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ideapin',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ideapin',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='ideapin',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
