# Generated by Django 4.2.4 on 2023-09-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_remove_pin_materials_remove_pin_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideapin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='idea_pins/'),
        ),
    ]
