# Generated by Django 4.2.4 on 2023-09-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_alter_ideapin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideapin',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
